Clarify the PMIx_Abort behavior
pmix/pmix-standard pull request #308
Opened 2020-11-20 15:35 UTC by rhc54

Deal with the edge cases of environments where not all use-cases are
supported (e.g., termination of a subset of a namespace, or termination
of processes outside of the caller's namespace)

Refs #307

Signed-off-by: Ralph Castain <rhc@pmix.org>

2020-11-23 15:29 UTC, jjhursey commented on Chap_API_Struct.tex
> +An incorrect or unsupported parameter was passed to a \ac{PMIx} \ac{API}.
This gets confusing when compared with the `PMIX_ERR_NOT_SUPPORTED` error code. If an unsupported parameter was passed then it should

2020-11-30 14:59 UTC, jjhursey commented on Chap_API_Struct.tex
> +An incorrect or unsupported parameter was passed to a \ac{PMIx} \ac{API}.
Since we have `PMIX_ERR_PARAM_VALUE_NOT_SUPPORTED` now, I don't think we want this change to the `PMIX_ERR_BAD_PARAM` definition.

2020-11-30 15:00 UTC, jjhursey requested changes
Looks good other than my request to revert the definition of `PMIX_ERR_BAD_PARAM`.

2020-11-30 16:19 UTC, rhc54 commented
> Looks good other than my request to revert the definition of `PMIX_ERR_BAD_PARAM`.

Yeah, I'm noodling over that one. Obviously, a "bad param" returned error doesn't mean you passed an incorrect type to us - the compiler would have to catch that one. We have now separated out the issue of passing a supported parameter with an unsupported value, so that isn't included here.

Seems to me that the other cases we need to cover are:

* passing a given attribute more than once, with non-matching values
* passing multiple attributes that result in conflicting directives
* passing an attribute that this function does not support/recognize, at least in this implementation and/or environment

I think we return `PMIX_ERR_NOT_SUPPORTED` for the last one, which should be fine. I think we should use `PMIX_ERR_BAD_PARAM` for the first two.

Does that make sense? If so, it might be worth adding some verbage to convey those cases.

2020-11-30 16:46 UTC, jjhursey commented
> > Looks good other than my request to revert the definition of `PMIX_ERR_BAD_PARAM`.
> 
> Yeah, I'm noodling over that one. Obviously, a "bad param" returned error doesn't mean you passed an incorrect type to us - the compiler would have to catch that one. We have now separated out the issue of passing a supported parameter with an unsupported value, so that isn't included here.

I think so. Could we say `An incorrect, conflicting, or invalid parameter was passed...`?

> * passing a given attribute more than once, with non-matching values

This would be a "conflicting" case for `PMIX_ERR_BAD_PARAM`

> * passing multiple attributes that result in conflicting directives

This would be a "conflicting" case for `PMIX_ERR_BAD_PARAM`

> * passing an attribute that this function does not support/recognize, at least in this implementation and/or environment

I would think this would be a `PMIX_ERR_NOT_SUPPORTED`

2020-11-30 17:33 UTC, rhc54 commented
Sounds like we are on the same wavelength - I'll try to provide an update in a bit.

2020-12-01 17:09 UTC, rhc54 commented
@jjhursey See what you think of the revision to `PMIX_ERR_BAD_PARAM`

2020-12-01 19:31 UTC, jjhursey approved these changes
This looks good to me

2020-12-01 20:21 UTC, merged