v5: Add revision history info, drop NEW markers
pmix/pmix-standard pull request #422
Opened 2022-08-22 20:29 UTC by raffenet

This PR contains 2 commits.
1. The review history section for v5 as presented at the Q3 2022 ASC meeting.
2. Drops all "NEW" markers for declarations in the document. As discussed at the same Q3 2022 meeting, these markers are error-prone, and somewhat obsolete with the addition of the revision history section. Consensus was to remove them from the document.

2022-09-02 16:18 UTC, jjhursey requested changes
Looks good. A few minor edits for the revision log

2022-09-02 16:18 UTC, jjhursey commented on Chap_Revisions.tex
> +  \item Clarify when PMIX_PARENT_ID attribute is provided.
```suggestion
  \item Clarify when \refattr{PMIX_PARENT_ID} attribute is provided.
```

2022-09-08 19:43 UTC, raffenet commented on Chap_Revisions.tex
> +  \item Add example C and Python PMIx client codes in sources/ directory.
That's fine with me. I was just going thru the PRs and went back and forth on whether this one belonged.

2022-09-13 13:59 UTC, jjhursey approved these changes

2022-11-07 17:54 UTC, raffenet commented
@jjhursey @dsolt I added 3 more minor commits to this branch since presenting at the quarterly. Please take a look.
1. simple typo fix
2. add reference to new Use-Cases appendix
3. add item about removing NEW from declarations

2022-11-08 15:50 UTC, jjhursey submitted a review, later dismissed

2022-11-08 15:50 UTC, jjhursey commented
This LGTM. I think if @dsolt is good with it then we can merge whenever you are ready.

2022-11-21 19:09 UTC, dsolt submitted a review, later dismissed

2022-11-21 19:34 UTC, merged